export {
  LEARNING_JOURNEY_STEPS,
  activeMilestoneCount,
  availableActions,
  createDraftContract,
  isStepActor,
  journeyStepIndex,
  reduceContract,
  waitingOn,
} from './learningContractMachine.js';
export type {
  ClientContractAction,
  ContractAction,
  ContractActionType,
  ContractActor,
  ContractEffect,
  ReduceResult,
} from './learningContractMachine.js';

export {
  TERMS_SECTIONS,
  TERMS_SUMMARY,
  TERMS_TITLE,
  TERMS_VERSION,
  needsTermsAcceptance,
} from './legal.js';
export type { TermsSection } from './legal.js';

export {
  COLLECTIONS,
  emptyLearnerProfile,
  emptyMentorProfile,
  isAccountActive,
} from './types.js';

export type {
  AccountRow,
  ApiError,
  ApplicationStatus,
  AdminCounts,
  CompetencyGoal,
  DeliverableRef,
  EducationEntry,
  ExperienceEntry,
  FirebaseClientStatus,
  HealthStatus,
  Deliverable,
  DeliverableStatus,
  Goal,
  IsoDateString,
  LearnerProfile,
  LearningContract,
  LearningContractStatus,
  MentorProfile,
  Milestone,
  MilestoneStatus,
  Objective,
  Mentorship,
  MentorshipApplication,
  MentorshipRelationship,
  MentorshipStatus,
  Message,
  PendingMentorRow,
  RelationshipStatus,
  Review,
  SignupRole,
  StepOwner,
  User,
  UserRole,
  VerificationDecision,
  VerificationStatus,
} from './types.js';

export {
  ADMIN_AUDIT_ACTION,
  AUDIT_EVENT,
  APPLICATION_MESSAGE,
  APPLICATION_STATUS,
  APPLICATION_TRANSITIONS,
  CANONICAL_LEARNER_ID_FIELD,
  CANONICAL_LEARNER_ROLE,
  DELIVERABLE_STATUS,
  EVIDENCE,
  LEARNING_CONTRACT_STATUS,
  LEARNING_CONTRACT_STATUS_LABEL,
  LEARNING_CONTRACT_TRANSITIONS,
  LEGACY_MENTORSHIP_STATUS,
  MESSAGE_TEXT,
  MILESTONE_STATUS,
  MILESTONE_TRANSITIONS,
  NOTIFICATION_STATUS,
  NOTIFICATION_TYPE,
  PAIRING_ID_FIELD,
  PUBLIC_LEARNER_LABEL,
  RELATIONSHIP_STATUS,
  RELATIONSHIP_STATUS_LABEL,
  RELATIONSHIP_TRANSITIONS,
  RESERVED_COLLECTIONS,
  SHOWCASE_SOURCE,
  STEP_OWNER,
  USER_ROLE,
  VERIFICATION_STATUS,
  VERIFICATION_TRANSITIONS,
  canAcceptApplication,
  canAdminister,
  canApplyForMentorship,
  canDecideVerification,
  canDeclineApplication,
  buildActiveRelationship,
  buildAuditLog,
  canEndRelationship,
  canPauseRelationship,
  canReadPairing,
  canResumeRelationship,
  canSendMessage,
  canStartLearningJourney,
  canSuspendAccount,
  canTerminateRelationship,
  canTransition,
  canTransitionApplication,
  canTransitionContract,
  canTransitionMilestone,
  canTransitionRelationship,
  canTransitionVerification,
  counterpartField,
  evidenceFromMilestone,
  findMilestoneByStatus,
  isActionableEvidenceMilestone,
  isActiveRelationship,
  isClosedRelationship,
  isOpenRelationship,
  isAdminRole,
  isApplicationStatus,
  isCompletedDeliverable,
  isContractActiveStatus,
  isContractCompleted,
  isContractInProgress,
  isDeliverableStatus,
  isEvidenceComplete,
  isLearnerReviewStatus,
  isLearnerRole,
  isLearnerStep,
  isLearningContractStatus,
  isMentorReviewStatus,
  isMentorRole,
  isMentorStep,
  isMilestoneStatus,
  isNegotiationOpen,
  isPairingMember,
  isPendingApplication,
  isRelationshipStatus,
  isSignupRole,
  isStepOwner,
  isSubmittedMilestone,
  isUnreadNotification,
  isUserRole,
  isVerificationStatus,
  learningGoalBuilderFromContract,
  nextActionCopy,
  normalizeContract,
  milestoneEvidence,
  normalizeRelationship,
  otherPartyId,
  pairingIdFieldForRole,
  pairingIdForAccount,
  profileCollectionForRole,
  relationshipDocId,
  showcaseFromDeliverableRef,
  showcasesFromProfile,
  sortMilestones,
  validateApplicationMessage,
  validateChangeRequestReason,
  validateEvidenceSubmission,
  validateGoalDraft,
  validateMentorPlan,
  validateMessageText,
  validateMilestoneFeedback,
} from './domain/index.js';

export type {
  AdminAuditAction,
  AdminAuditLog,
  AuditEvent,
  CollectionName,
  Evidence,
  ContractRevision,
  LearningGoalBuilder,
  MentorApplication,
  Notification,
  NotificationType,
  PairingIdField,
  PairingMemberIds,
  PermissionActor,
  ReservedCollectionName,
  ShowcaseItem,
  ShowcaseSource,
  TransitionMap,
  ValidationResult,
} from './domain/index.js';
